import 'package:intl/intl.dart';

/// Represents a single challenge entry stored in the `challenges` Supabase table.
///
/// Column mapping:
/// ```
/// id           uuid   PK  generated by Supabase
/// user_id      uuid   FK  auth.users.id
/// date         date
/// problem      text
/// resolution   text
/// created_at   timestamptz  default now()
/// ```
class Challenge {
  final String id;
  final String userId;
  final DateTime date;
  final String problem;
  final String resolution;
  final String lessonsLearned;

  const Challenge({
    required this.id,
    required this.userId,
    required this.date,
    required this.problem,
    required this.resolution,
    required this.lessonsLearned,
  });

  factory Challenge.fromJson(Map<String, dynamic> json) {
    return Challenge(
      id:             json['id']             as String,
      userId:         json['user_id']        as String,
      date:           DateTime.parse(json['date'] as String),
      problem:        json['problem']        as String,
      resolution:     json['resolution']     as String? ?? '',
      lessonsLearned: json['lessons_learned'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'user_id':         userId,
      'date':            DateFormat('yyyy-MM-dd').format(date),
      'problem':         problem,
      'resolution':      resolution,
      'lessons_learned': lessonsLearned,
    };
  }

  Challenge copyWith({
    String? id,
    String? userId,
    DateTime? date,
    String? problem,
    String? resolution,
    String? lessonsLearned,
  }) {
    return Challenge(
      id:             id             ?? this.id,
      userId:         userId         ?? this.userId,
      date:           date           ?? this.date,
      problem:        problem        ?? this.problem,
      resolution:     resolution     ?? this.resolution,
      lessonsLearned: lessonsLearned ?? this.lessonsLearned,
    );
  }
}
