import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

// ── Task type enum ────────────────────────────────────────────────────────────

enum TaskType {
  fieldWork,
  officeWork,
  software;

  /// Display label — also the value stored in the `task_type` DB column.
  String get label {
    switch (this) {
      case TaskType.fieldWork:  return 'Field Work';
      case TaskType.officeWork: return 'Office Work';
      case TaskType.software:   return 'Software';
    }
  }

  /// Short example subtitle shown in the form picker.
  String get example {
    switch (this) {
      case TaskType.fieldWork:  return 'e.g. Concrete Pouring, Site Inspection';
      case TaskType.officeWork: return 'e.g. Quantity Surveying, Report Writing';
      case TaskType.software:   return 'e.g. AutoCAD, Revit, SAP2000';
    }
  }

  /// Icon used in cards and the form.
  IconData get icon {
    switch (this) {
      case TaskType.fieldWork:  return Icons.construction_rounded;
      case TaskType.officeWork: return Icons.business_center_rounded;
      case TaskType.software:   return Icons.computer_rounded;
    }
  }

  /// Foreground colour for badges / chips.
  Color get color {
    switch (this) {
      case TaskType.fieldWork:  return const Color(0xFF2E7D32);
      case TaskType.officeWork: return const Color(0xFF1565C0);
      case TaskType.software:   return const Color(0xFF6A1B9A);
    }
  }

  /// Background colour for badges / chips.
  Color get bgColor {
    switch (this) {
      case TaskType.fieldWork:  return const Color(0xFFE8F5E9);
      case TaskType.officeWork: return const Color(0xFFE3F2FD);
      case TaskType.software:   return const Color(0xFFF3E5F5);
    }
  }

  /// Parses a raw DB string back into a [TaskType].
  static TaskType fromString(String value) {
    switch (value) {
      case 'Field Work':  return TaskType.fieldWork;
      case 'Office Work': return TaskType.officeWork;
      case 'Software':    return TaskType.software;
      default:            return TaskType.fieldWork;
    }
  }
}

// ── DailyLog model ────────────────────────────────────────────────────────────

/// Represents a single daily training log entry stored in the `daily_logs`
/// Supabase table.
///
/// Column mapping:
/// ```
/// id           uuid   PK  generated by Supabase (excluded from toJson inserts)
/// user_id      uuid   FK  auth.users.id
/// date         date
/// task_type    text        'Field Work' | 'Office Work' | 'Software'
/// description  text
/// issues_found text
/// image_url    text   nullable
/// created_at   timestamptz  default now()
/// ```
class DailyLog {
  final String id;          // UUID assigned by Supabase; empty for unsaved rows
  final String userId;
  final DateTime date;
  final TaskType taskType;
  final String description;
  final String issuesFound;
  final String? imageUrl;
  final String approvalStatus;

  const DailyLog({
    required this.id,
    required this.userId,
    required this.date,
    required this.taskType,
    required this.description,
    required this.issuesFound,
    this.imageUrl,
    this.approvalStatus = 'pending',
  });

  // ── Serialisation ─────────────────────────────────────────────────────────

  /// Creates a [DailyLog] from a Supabase row map.
  factory DailyLog.fromJson(Map<String, dynamic> json) {
    return DailyLog(
      id:          json['id']           as String,
      userId:      json['user_id']      as String,
      date:        DateTime.parse(json['date'] as String),
      taskType:    TaskType.fromString(json['task_type'] as String),
      description: json['description']  as String,
      issuesFound: json['issues_found'] as String? ?? '',
      imageUrl:    json['image_url']    as String?,
      approvalStatus: json['approval_status'] as String? ?? 'pending',
    );
  }

  /// Serialises this log for a Supabase INSERT.
  ///
  /// The `id` column is intentionally omitted — Supabase generates it via
  /// `gen_random_uuid()`. The `created_at` column uses a DB default.
  Map<String, dynamic> toJson() {
    return {
      'user_id':      userId,
      'date':         DateFormat('yyyy-MM-dd').format(date),
      'task_type':    taskType.label,
      'description':  description,
      'issues_found': issuesFound,
      'approval_status': approvalStatus,
      if (imageUrl != null) 'image_url': imageUrl,
    };
  }

  /// Returns a copy of this log with the given fields replaced.
  DailyLog copyWith({
    String? id,
    String? userId,
    DateTime? date,
    TaskType? taskType,
    String? description,
    String? issuesFound,
    String? imageUrl,
    String? approvalStatus,
  }) {
    return DailyLog(
      id:          id          ?? this.id,
      userId:      userId      ?? this.userId,
      date:        date        ?? this.date,
      taskType:    taskType    ?? this.taskType,
      description: description ?? this.description,
      issuesFound: issuesFound ?? this.issuesFound,
      imageUrl:    imageUrl    ?? this.imageUrl,
      approvalStatus: approvalStatus ?? this.approvalStatus,
    );
  }
}

// ── Placeholder data ──────────────────────────────────────────────────────────
// Used as an offline fallback while Supabase auth is not yet configured.

final List<DailyLog> placeholderLogs = [
  DailyLog(
    id: 'placeholder-1',
    userId: '',
    date: DateTime(2026, 6, 15),
    taskType: TaskType.fieldWork,
    description:
        'Supervised concrete pouring for the ground floor slab of Block A. '
        'Verified slump test results met spec (100 mm ±25 mm). Coordinated '
        'with contractor to ensure proper vibration and finishing.',
    issuesFound:
        'Slight delay due to concrete pump malfunction. Resolved by '
        'requesting a backup pump. Finished ~2 hours behind schedule.',
    imageUrl: null,
  ),
  DailyLog(
    id: 'placeholder-2',
    userId: '',
    date: DateTime(2026, 6, 14),
    taskType: TaskType.officeWork,
    description:
        'Prepared quantity take-off for reinforcement steel in columns '
        'C1–C12. Cross-referenced against the approved structural drawings Rev. 3.',
    issuesFound:
        'Discrepancy found in rebar diameter for column C7 — drawing '
        'shows Ø16 but schedule listed Ø20. Flagged to structural engineer.',
    imageUrl: null,
  ),
  DailyLog(
    id: 'placeholder-3',
    userId: '',
    date: DateTime(2026, 6, 13),
    taskType: TaskType.software,
    description:
        'Modelled staircase core walls in Revit 2024 for coordination with '
        'the MEP team. Exported IFC file for clash detection in Navisworks.',
    issuesFound:
        'Wall thickness mismatch between architectural and structural '
        'models at Level 2. Raised a BIM coordination issue and scheduled a '
        'clash review meeting.',
    imageUrl: null,
  ),
  DailyLog(
    id: 'placeholder-4',
    userId: '',
    date: DateTime(2026, 6, 12),
    taskType: TaskType.fieldWork,
    description:
        'Conducted formwork inspection for ground floor columns prior to '
        'rebar placement. Checked alignment, plumb, and bracing per IS 14687.',
    issuesFound:
        'Three column forms were out of plumb by >3 mm. Instructed '
        'foreman to re-align; re-inspected and approved.',
    imageUrl: null,
  ),
  DailyLog(
    id: 'placeholder-5',
    userId: '',
    date: DateTime(2026, 6, 11),
    taskType: TaskType.officeWork,
    description:
        'Attended weekly progress meeting with PM and subcontractors. '
        'Recorded minutes and tracked outstanding action items.',
    issuesFound:
        'Delayed material delivery for waterproofing membrane. Action: '
        'expedite PO and arrange alternative supplier quotes by Thursday.',
    imageUrl: null,
  ),
  DailyLog(
    id: 'placeholder-6',
    userId: '',
    date: DateTime(2026, 6, 10),
    taskType: TaskType.software,
    description:
        'Ran structural analysis on SAP2000 for the transfer beam at '
        'Level 3. Verified deflection and moment capacity under worst-case '
        'load combination (1.2D + 1.6L).',
    issuesFound:
        'Deflection under D+L exceeded L/360 limit. After review with '
        'senior engineer, section increased from 400×800 to 400×1000 mm.',
    imageUrl: null,
  ),
];
